apiVersion: 1
datasources:
  - name: ECE-IoT
    type: grafana-timestream-datasource
    jsonData:
        authType: keys
        defaultRegion: eu-central-1
    secureJsonData:
        accessKey: Access
        secretKey: Secret
