apiVersion: 1
datasources:
  - name: ECE-IoT
    type: grafana-timestream-datasource
    jsonData:
    authType: keys
    defaultRegion: us-east-1
    secureJsonData:
    accessKey: '123456'
    secretKey: '5255'
